name: Hello
description: 元気に挨拶してくれる画期的すぎるアクションです
inputs:
  target:
    description: あなたが挨拶したいのは誰ですか？
outputs:
  target:
    value: ${{ inputs.target }}
    description: 挨拶した相手
runs:
  using: composite
  steps:
    - run: |
          echo "Hello, ${TARGET}!"
          echo "${{ runner.temp }}/flutter/bin" >> $GITHUB_PATH
          echo "${{ runner.temp }}/flutter/.pub-cache/bin" >> $GITHUB_PATH
          echo "FLUTTER_PATH=${{ runner.temp }}/flutter" >> $GITHUB_ENV
          echo "PUB_CACHE=${{ runner.temp }}/flutter/.pub-cache" >> $GITHUB_ENV
      shell: bash
      env:
        TARGET: ${{ inputs.target }}
