name: call job summary

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  caller-jobname:
    uses: ./.github/workflows/job-summary.yml
    secrets: inherit
    with:
      code-sign-style: auto
      upload-artifact: true
