name: job-condition-executing

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  target: ok # ok or ng

jobs:
  pre-process:
    runs-on: ubuntu-latest
    steps:
      - id: check
        run: |
          echo "condition=$target" >> $GITHUB_OUTPUT
    outputs:
      target-job: ${{ steps.check.outputs.condition }}

  ok:
    runs-on: ubuntu-latest
    needs: [pre-process]
    if: needs.pre-process.outputs.target-job == 'ok'
    steps:
      - run: echo "ok"
      - run: exit 1

  ng:
    runs-on: ubuntu-latest
    needs: [pre-process]
    if: needs.pre-process.outputs.target-job == 'ng'
    steps:
      - run: echo "ng"
      - run: exit 1

  post-process:
    runs-on: ubuntu-latest
    needs: [ok, ng]
    # if: ${{ always() && contains(needs.*.result, 'success') }}
    # if: contains(needs.ok.result, 'success')
    # if: contains(needs.*.result, 'success')
    # if: ${{ needs.ok.result == 'success' || needs.ng.result == 'success' }}
    # if: ${{ needs.ok.result == 'success' }}
    # if: |
    #   always() &&
    #   ((needs.ok.result == 'success' && needs.ng.result == 'skipped') ||
    #   (needs.ok.result == 'skipped' && needs.ng.result == 'success'))
    if: always() && contains(needs.*.result, 'success')
    steps:
      - run: echo "post-process"
