name: job-condition-executing

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  target: job1

jobs:
  CheckEnvJob:
    runs-on: ubuntu-latest
    steps:
      - name: check-env
        id: check-env
        run: |
          ENV=$(sh ./check-env.sh)
          echo '::set-output name=ENV::${ENV}'
    outputs:
      env: $ {{ steps.check-env.outputs.ENV }}

  # dev環境用にfork
  DevJob:
    runs-on: ubuntu-latest
    needs: CheckEnvJob
    if: needs.CheckEnvJob.outputs.env == 'dev' # if文を書くのはここ1回だけ
    steps:
      - name: dev-step-1
      - name: dev-step-2

  # prd環境用にfork
  PrdJob:
    runs-on: ubuntu-latest
    needs: CheckEnvJob
    if: needs.CheckEnvJob.outputs.env == 'prd' # if文を書くのはここ1回だけ
    steps:
      - name: prd-step-1
      - name: prd-step-2

  # dev, prd環境個別の処理が終わってjoin
  JoinedJob:
    runs-on: ubuntu-latest
    needs: [DevJob, PrdJob]
    if: always() && contains(needs.*.result, 'success') # if文を書くのはここ1回だけ
    steps:
      - name: join-step-1
      - name: join-step-2

    # (補足)
    # if: contains(needs.*.result, 'success')は以下と同値です
    # if: (needs.DevJob.result == 'success' || needs.PrdJob.result == 'success')
