name: job-condition-executing

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CheckEnvJob:
    runs-on: ubuntu-latest
    steps:
      - name: check-env
        id: check-env
        run: |
          echo 'env=dev' >> $GITHUB_OUTPUT
    outputs:
      env: ${{ steps.check-env.outputs.env }}

  DevJob:
    runs-on: ubuntu-latest
    needs: [CheckEnvJob]
    if: needs.CheckEnvJob.outputs.env == 'dev'
    steps:
      - run: echo dev-step-1
      - run: echo dev-step-2

  PrdJob:
    runs-on: ubuntu-latest
    needs: [CheckEnvJob]
    if: needs.CheckEnvJob.outputs.env == 'prd'
    steps:
      - run: echo prd-step-1
      - run: echo prd-step-2

  JoinedJob:
    runs-on: ubuntu-latest
    needs: [DevJob, PrdJob]
    if: always() && contains(needs.*.result, 'success')
    steps:
      - run: echo join-step-1
      - run: echo join-step-2
