name: job-condition-executing

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  target: job1

jobs:
  pre-process:
    runs-on: ubuntu-latest
    steps:
      - id: check
        run: echo "condition=$target" >> $GITHUB_OUTPUT
    outputs:
      target-job: ${{ steps.check.outputs.condition }}

  job1:
    runs-on: ubuntu-latest
    needs: [pre-process]
    if: needs.pre-process.outputs.target-job == 'job1'
    steps:
      - run: echo "job1"
      - run: exit 1

  job2:
    runs-on: ubuntu-latest
    needs: [pre-process]
    if: needs.pre-process.outputs.target-job == 'job2'
    steps:
      - run: echo "job2"
      - run: exit 1

  post-process:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always() && contains(needs.*.result, 'success')
    # if: |
    #   always() &&
    #   ((needs.job1.result == 'success' && needs.job2.result == 'skipped') ||
    #   (needs.job1.result == 'skipped' && needs.job2.result == 'success'))
    steps:
      - run: echo "post-process"
