name: job-condition-executing

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  your_condition: ok # ok or ng

jobs:
  pre-process:
    runs-on: ubuntu-latest
    steps:
      - id: check_condition
        run: |
          echo "condition=$your_condition" >> $GITHUB_OUTPUT
    outputs:
      condition_result: ${{ steps.check_condition.outputs.condition }}

  ok:
    runs-on: ubuntu-latest
    needs: [pre-process]
    if: needs.pre-process.outputs.condition_result == 'ok'
    steps:
      - run: echo "ok"
      - run: |
          exit 1

  ng:
    runs-on: ubuntu-latest
    needs: [pre-process]
    if: needs.pre-process.outputs.condition_result == 'ng'
    steps:
      - run: echo "ng"
      # - run: |
      #     exit 1

  post-process:
    runs-on: ubuntu-latest
    needs: [ok, ng]
    # if: ${{ always() && contains(needs.*.result, 'success') }}
    # if: contains(needs.ok.result, 'success')
    # if: contains(needs.*.result, 'success')
    # if: ${{ needs.ok.result == 'success' || needs.ng.result == 'success' }}
    # if: ${{ needs.ok.result == 'success' }}
    # if: |
    #   always() &&
    #   ((needs.ok.result == 'success' && needs.ng.result == 'skipped') ||
    #   (needs.ok.result == 'skipped' && needs.ng.result == 'success'))
    if: always() && contains(needs.*.result, 'success')
    steps:
      - run: echo "post-process"
