name: pr-ci-repo-state
on:
  pull_request:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          echo hello
          cat README.md
          cat test.md
